# Generated by Django 3.2.18 on 2023-03-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0004_auto_20230309_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.IntegerField(choices=[(0, 'Service'), (1, 'Request')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(),
        ),
    ]
