# Generated by Django 3.2.18 on 2023-03-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0008_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
