# Generated by Django 3.2.18 on 2023-03-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0010_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=55),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
