# Generated by Django 3.2.18 on 2023-04-05 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workapp', '0011_auto_20230315_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blurb',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='PostReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=55)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=10000)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(choices=[(0, '0'), (0.5, '0.5'), (1, '1'), (1.5, '1.5'), (2, '2'), (2.5, '2.5'), (3, '3'), (3.5, '3.5'), (4, '4'), (4.5, '4.5'), (5, '5')], decimal_places=1, max_digits=2)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_review', to='workapp.post')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
