# Generated by Django 3.2.18 on 2023-04-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0012_auto_20230405_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=4000),
        ),
    ]
