# Generated by Django 3.2.18 on 2023-04-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0013_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postreview',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
