# Generated by Django 3.2.18 on 2023-04-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0014_auto_20230410_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AddField(
            model_name='post',
            name='contact_info',
            field=models.TextField(default='contact@test.com', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Per Hour'), (1, 'Total Payment')], default=0),
        ),
    ]
